name: Build Test Kernel

on:
  workflow_dispatch:
    inputs:
      toolchain:
        description: "Toolchain (llvm-mingw, google-ndk, llvm-22.1.8, llvm-23.1.0-rc2, neutron-clang)"
        required: false
        default: "google-ndk"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        device: [ c1q , c2q , y2q ]

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential bc bison flex libssl-dev \
            gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi \
            binutils-aarch64-linux-gnu \
            python3 adb zip curl xz-utils \
            llvm lld dwarves git unzip wget zstd jq ccache

      - name: Download selected toolchain
        run: |
          ROOT_DIR="$(pwd)"
          TOOLCHAIN_DIR="$ROOT_DIR/toolchains"
          mkdir -p "$TOOLCHAIN_DIR"

          case "${{ github.event.inputs.toolchain }}" in
            llvm-mingw)
              TOOLCHAIN_NAME="llvm-mingw"
              CLANG_TARBALL="llvm-mingw-20260728-ucrt-ubuntu-22.04-x86_64.tar.xz"
              CLANG_URL="https://github.com/mstorsjo/llvm-mingw/releases/download/20260728/$CLANG_TARBALL"
              ;;
            google-ndk)
              TOOLCHAIN_NAME="google-ndk"
              CLANG_TARBALL="clang-linux-x86-ndk-r29-r563880c.tar.zst"
              CLANG_URL="https://github.com/Ylarod/setup-ndk-clang/releases/download/prebuilt/$CLANG_TARBALL"
              ;;
            llvm-22.1.8)
              TOOLCHAIN_NAME="llvm-22.1.8"
              CLANG_TARBALL="LLVM-22.1.8-Linux-X64.tar.xz"
              CLANG_URL="https://github.com/llvm/llvm-project/releases/download/llvmorg-22.1.8/$CLANG_TARBALL"
              ;;
            llvm-23.1.0-rc2)
              TOOLCHAIN_NAME="llvm-23.1.0-rc2"
              CLANG_TARBALL="llvm-project-23.1.0-rc2.src.tar.xz"
              CLANG_URL="https://github.com/llvm/llvm-project/releases/download/llvmorg-23.1.0-rc2/$CLANG_TARBALL"
              ;;
            neutron-clang)
              TOOLCHAIN_NAME="neutron-clang"
              TC_DIR="$TOOLCHAIN_DIR/$TOOLCHAIN_NAME"
              if ! [ -d "$TC_DIR" ]; then
                echo "Clang not found! Downloading Neutron Clang..."
                mkdir -p "$TC_DIR"
                ASSET_URL=$(
                  curl -fsSL https://api.github.com/repos/Neutron-Toolchains/clang-build-catalogue/releases/latest |
                  jq -r '.assets[] | select(.name | endswith(".tar.zst")) | .browser_download_url' |
                  head -n1
                )
                if [ -z "$ASSET_URL" ]; then
                  echo "Failed to find latest Neutron Clang release!"
                  exit 1
                fi
                if ! curl -L "$ASSET_URL" | tar --zstd -x -C "$TC_DIR" --strip-components=1; then
                  echo "Download failed!"
                  exit 1
                fi
                echo "Neutron Clang ready!"
              fi
              ;;
            *)
              echo "Unknown toolchain option!"
              exit 1
              ;;
          esac

          TC_DIR="$TOOLCHAIN_DIR/$TOOLCHAIN_NAME"
          echo "TOOLCHAIN_DIR=$TC_DIR" >> $GITHUB_ENV
          echo "TOOLCHAIN_NAME=$TOOLCHAIN_NAME" >> $GITHUB_ENV

      - name: Build kernel
        run: |
          chmod +x build_test.sh
          bash build_test.sh \
            "${{ matrix.device }}" \
            "$TOOLCHAIN_DIR/$TOOLCHAIN_NAME"

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: Astro-Kernel-${{ matrix.device }}-${{ env.TOOLCHAIN_NAME }}
          path: Astro-Kernel-${{ matrix.device }}-${{ env.TOOLCHAIN_NAME }}-*.zip
